### ISSUE TITLE
Too strict version bounds on base and optparse-applicative

### ISSUE THREAD

**Issue by lf-** [edsko/friendly#5]
Building friendly in nixpkgs with ghc9 results in the following error:

```
       > Setup: Encountered missing or private dependencies:
       > base >=4.7 && <4.15, optparse-applicative >=0.11 && <0.16
```

This environment has base=4.15 and optparse-applicative=0.16 and friendly builds on it. Can you relax these bounds? Thanks.

**Comment by edsko** [comment]
Done, now builds with 9.0 and 9.2.
